export const ROLES = Object.freeze({
  SUPER_ADMIN: "SUPER_ADMIN",
  COMPANY_ADMIN: "COMPANY_ADMIN",
  RECRUITER: "RECRUITER",
  AGENT: "AGENT",
});

export const COMPANY_ROLES = [ROLES.COMPANY_ADMIN, ROLES.RECRUITER, ROLES.AGENT];

export const CANDIDATE_STATUS = Object.freeze({
  NEW: "NEW",
  SCREENING: "SCREENING",
  INTERVIEW: "INTERVIEW",
  SELECTED: "SELECTED",
  REJECTED: "REJECTED",
});

export const CALL_TYPE = Object.freeze({
  INBOUND: "INBOUND",
  OUTBOUND: "OUTBOUND",
});

export const CALL_STATUS = Object.freeze({
  INITIATED: "INITIATED",
  RINGING: "RINGING",
  CONNECTED: "CONNECTED",
  MISSED: "MISSED",
  FAILED: "FAILED",
  COMPLETED: "COMPLETED",
});

export const FOLLOWUP_STATUS = Object.freeze({
  PENDING: "PENDING",
  COMPLETED: "COMPLETED",
});

export const CAMPAIGN_STATUS = Object.freeze({
  DRAFT: "DRAFT",
  ACTIVE: "ACTIVE",
  PAUSED: "PAUSED",
  COMPLETED: "COMPLETED",
});

export const SUBSCRIPTION_PLANS = Object.freeze({
  FREE: "FREE",
  STARTER: "STARTER",
  GROWTH: "GROWTH",
  ENTERPRISE: "ENTERPRISE",
});

export const SUBSCRIPTION_STATUS = Object.freeze({
  TRIAL: "TRIAL",
  ACTIVE: "ACTIVE",
  PAST_DUE: "PAST_DUE",
  SUSPENDED: "SUSPENDED",
  CANCELLED: "CANCELLED",
});

export const PLAN_CREDITS = Object.freeze({
  FREE: 50,
  STARTER: 500,
  GROWTH: 2500,
  ENTERPRISE: 10000,
});

export const NOTIFICATION_TYPES = Object.freeze({
  CANDIDATE_CREATED: "CANDIDATE_CREATED",
  CALL_UPDATED: "CALL_UPDATED",
  FOLLOWUP_REMINDER: "FOLLOWUP_REMINDER",
  CAMPAIGN_UPDATED: "CAMPAIGN_UPDATED",
  SYSTEM: "SYSTEM",
});

export const PAGINATION = Object.freeze({
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 20,
  MAX_LIMIT: 100,
});
